site_name: SportOrg
site_url: https://sportorg.readthedocs.io/ru/latest/
site_description: 'SportOrg - программное обеспечение для организации соревнований. Поддержка электронных систем отметки SPORTIdent, SFR, SportIduino'

repo_name: 'sportorg-docs'
repo_url: 'https://github.com/sportorg/sportorg-docs'

copyright: 'Copyright &copy; 2018 SportOrg'

theme:
  name: readthedocs
  language: ru

plugins:
- search:
    lang: ru

nav:
- 'Главная': index.md
- 'Гид пользователя':
  - user-guide/get-started.md
  - user-guide/import-data.md
  - user-guide/start.md
  - user-guide/finish.md
  - user-guide/course.md
  - user-guide/sportident.md
  - user-guide/winorient.md
  - user-guide/teamwork.md
  - user-guide/templates.md
  - user-guide/maze.md
  - user-guide/liveorg.md
- 'FAQ': faq/index.md
- 'О нас':
  - about/contributors.md
  - 'License': about/LICENSE.md
  - about/changelog.md