site_name: SportOrg
site_description: 'SportOrg - программа для организации соревнований'

repo_name: 'sportorg-docs'
repo_url: 'https://github.com/sportorg/sportorg-docs'

copyright: 'Copyright &copy; 2018 SportOrg'

pages:
- 'Главная': index.md
- 'Гид пользователя': user-guide/index.md
- 'FAQ': faq/index.md
- 'О нас':
  - 'Разработчики': about/contributors.md
  - 'License': about/LICENSE.md
  - 'Список изменений': about/changelog.md