name: Github pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install python dependencies
        run: make install-poetry install

      - name: Build
        run: make docs
